-- CONFIRMED 2026-09-26 (Dan): WoW: Forever has no Jewelcrafting at present -- no gem sockets on
-- any item, nothing to socket into them. The 2400+ lines of WotLK/Triumvirate gem data this file
-- used to hold are inapplicable for two independent reasons (Triumvirate cancelled, and even if
-- it weren't, Forever has no gems at all), so it's been cleared rather than left as dead weight
-- loaded on every startup. Removed from TopFit.toc's load order entirely for the same reason --
-- there's nothing here to load.
--
-- TopFit:GetBestGemScore (calculation.lua) already handles an empty/nil TopFit.gemIDs
-- gracefully (returns 0), and TopFit:GetPotentialGemScore short-circuits to 0 whenever an item
-- has no empty socket colors -- which will always be true here, since no Forever item has
-- sockets. No other code changes were needed for this to be safe.
--
-- If Jewelcrafting is ever added to Forever, this is where real gem data would go, in the same
-- {gemID = {colors = {...}, stats = {...}}} shape as before.
TopFit.gemIDs = {}
