-- Auto-extracted from simc-335-1's sc_unique_gear.cpp (get_equip_encoding / get_hidden_encoding /
-- get_use_encoding). Keyed by TopFit:Slugify(itemName) to match simc's own item-name convention.
--
-- IMPORTANT: item NAMES match Triumvirate's items (same items reused), but the numeric AMOUNT in
-- these encoded strings reflects retail Wrath values, which Triumvirate may have retuned for its
-- level-60 cap. Only the *structure* here (trigger type, proc chance/PPM, duration, cooldown,
-- stacking behavior) should be trusted -- always prefer a tooltip-parsed amount when one is found.
--
-- Encoded string grammar (tokens separated by "_"):
--   [Trigger]_<amount><StatOrSchool>_[chance%|PPM|Stack]_[durDur]_[cdCd]_[tickTick]_[reverse]
-- Trigger e.g. OnAttackHit/OnAttackCrit/OnSpellCast/OnSpellCastHit/OnSpellCastMiss/OnSpellCrit/
-- OnSpellDirectHit/OnSpellDirectCrit/OnSpellDamage/OnSpellTickDamage/OnDamage. Absent for get_use_
-- encoding's simple activated trinkets (no proc trigger -- it's player-activated on its own Cd).
-- "normal"/"heroic" hold separate strings only where Triumvirate might have distinct heroic loot;
-- if only "normal" is present, the same string applies regardless of item quality variant.
TopFit.SimcProcData = {
	["equip"] = {
		["abyssal_rune"] = { normal = "OnSpellCast_590SP_25%_10Dur_45Cd" },
		["ashen_band_of_endless_destruction"] = { normal = "OnSpellCastHit_285SP_10%_10Dur_60Cd" },
		["ashen_band_of_endless_might"] = { normal = "OnAttackHit_480AP_1PPM_10Dur_60Cd" },
		["ashen_band_of_endless_vengeance"] = { normal = "OnAttackHit_480AP_1PPM_10Dur_60Cd" },
		["ashen_band_of_unmatched_destruction"] = { normal = "OnSpellCastHit_285SP_10%_10Dur_60Cd" },
		["ashen_band_of_unmatched_might"] = { normal = "OnAttackHit_480AP_1PPM_10Dur_60Cd" },
		["ashen_band_of_unmatched_vengeance"] = { normal = "OnAttackHit_480AP_1PPM_10Dur_60Cd" },
		["bandits_insignia"] = { normal = "OnAttackHit_1880Arcane_15%_45Cd" },
		["banner_of_victory"] = { normal = "OnAttackHit_1008AP_20%_10Dur_50Cd" },
		["black_magic"] = { normal = "OnSpellDirectHit_250Haste_35%_10Dur_35Cd" },
		["blood_of_the_old_god"] = { normal = "OnAttackCrit_1284AP_10%_10Dur_50Cd" },
		["bryntroll_the_bone_arbiter"] = { normal = "OnAttackHit_2250Drain_11%", heroic = "OnAttackHit_2538Drain_11%" },
		["charred_twilight_scale"] = { normal = "OnSpellCast_763SP_10%_15Dur_45Cd", heroic = "OnSpellCast_861SP_10%_15Dur_45Cd" },
		["chuchus_tiny_box_of_horrors"] = { normal = "OnAttackHit_258Crit_15%_10Dur_45Cd" },
		["comets_trail"] = { normal = "OnAttackHit_726Haste_10%_10Dur_45Cd" },
		["corens_chromium_coaster"] = { normal = "OnAttackCrit_1000AP_10%_10Dur_50Cd" },
		["dark_matter"] = { normal = "OnAttackHit_612Crit_15%_10Dur_45Cd" },
		["darkglow_embroidery"] = { normal = "OnSpellCast_400Mana_35%_60Cd" },
		["darkmoon_card_crusade"] = { normal = "OnDamage_8SP_10Stack_10Dur" },
		["dislodged_foreign_object"] = { normal = "OnSpellCast_105SP_10Stack_10%_20Dur_45Cd_2Tick", heroic = "OnSpellCast_121SP_10Stack_10%_20Dur_45Cd_2Tick" },
		["dying_curse"] = { normal = "OnSpellCast_765SP_15%_10Dur_45Cd" },
		["elemental_focus_stone"] = { normal = "OnSpellCast_522Haste_10%_10Dur_45Cd" },
		["embrace_of_the_spider"] = { normal = "OnSpellCast_505Haste_10%_10Dur_45Cd" },
		["extract_of_necromantic_power"] = { normal = "OnSpellTickDamage_1050Shadow_10%_15Cd" },
		["eye_of_magtheridon"] = { normal = "OnSpellCastMiss_170SP_10Dur" },
		["eye_of_the_broodmother"] = { normal = "OnSpellDamage_25SP_5Stack_10Dur" },
		["flare_of_the_heavens"] = { normal = "OnSpellCast_850SP_10%_10Dur_45Cd" },
		["forge_ember"] = { normal = "OnSpellCastHit_512SP_10%_10Dur_45Cd" },
		["fury_of_the_five_flights"] = { normal = "OnAttackHit_16AP_20Stack_10Dur" },
		["grim_toll"] = { normal = "OnAttackHit_612ArPen_15%_10Dur_45Cd" },
		["herkuml_war_token"] = { normal = "OnAttackHit_17AP_20Stack_10Dur" },
		["illustration_of_the_dragon_soul"] = { normal = "OnSpellCast_20SP_10Stack_10Dur" },
		["lightning_capacitor"] = { normal = "OnSpellDirectCrit_750Nature_3Stack_2.5Cd" },
		["lightweave"] = { normal = "OnSpellCast_295SP_35%_15Dur_60Cd" },
		["lightweave_embroidery"] = { normal = "OnSpellCast_295SP_35%_15Dur_60Cd" },
		["mark_of_defiance"] = { normal = "OnSpellCastHit_150Mana_15%_15Cd" },
		["mirror_of_truth"] = { normal = "OnAttackCrit_1000AP_10%_10Dur_50Cd" },
		["mithril_pocketwatch"] = { normal = "OnSpellCast_590SP_10%_10Dur_45Cd" },
		["mjolnir_runestone"] = { normal = "OnAttackHit_665ArPen_15%_10Dur_45Cd" },
		["muradins_spyglass"] = { normal = "OnSpellDamage_18SP_10Stack_10Dur", heroic = "OnSpellDamage_20SP_10Stack_10Dur" },
		["needleencrusted_scorpion"] = { normal = "OnAttackCrit_678ArPen_10%_10Dur_50Cd" },
		["pandoras_plea"] = { normal = "OnSpellCast_751SP_10%_10Dur_45Cd" },
		["phylactery_of_the_nameless_lich"] = { normal = "OnSpellTickDamage_1073SP_30%_20Dur_100Cd", heroic = "OnSpellTickDamage_1206SP_30%_20Dur_100Cd" },
		["purified_lunar_dust"] = { normal = "OnSpellCast_304MP5_10%_15Dur_45Cd" },
		["pyrite_infuser"] = { normal = "OnAttackCrit_1234AP_10%_10Dur_50Cd" },
		["quagmirrans_eye"] = { normal = "OnSpellCast_320Haste_10%_6Dur_45Cd" },
		["reign_of_the_dead"] = { normal = "OnSpellDirectCrit_1882Fire_3Stack_2.0Cd", heroic = "OnSpellDirectCrit_2117Fire_3Stack_2.0Cd" },
		["reign_of_the_unliving"] = { normal = "OnSpellDirectCrit_1882Fire_3Stack_2.0Cd", heroic = "OnSpellDirectCrit_2117Fire_3Stack_2.0Cd" },
		["rune_of_razorice"] = { normal = "custom" },
		["rune_of_the_fallen_crusader"] = { normal = "custom" },
		["sextant_of_unstable_currents"] = { normal = "OnSpellCrit_190SP_20%_15Dur_45Cd" },
		["sharpened_twilight_scale"] = { normal = "OnAttackHit_1304AP_35%_15Dur_45Cd", heroic = "OnAttackHit_1472AP_35%_15Dur_45Cd" },
		["shiffars_nexus_horn"] = { normal = "OnSpellCrit_225SP_20%_10Dur_45Cd" },
		["solace_of_the_defeated"] = { normal = "OnSpellCast_16MP5_8Stack_10Dur", heroic = "OnSpellCast_18MP5_8Stack_10Dur" },
		["solace_of_the_fallen"] = { normal = "OnSpellCast_16MP5_8Stack_10Dur", heroic = "OnSpellCast_18MP5_8Stack_10Dur" },
		["sundial_of_the_exiled"] = { normal = "OnSpellCast_590SP_10%_10Dur_45Cd" },
		["swordguard_embroidery"] = { normal = "OnAttackHit_400AP_25%_60Cd" },
		["thunder_capacitor"] = { normal = "OnSpellDirectCrit_1276Nature_4Stack_2.5Cd" },
		["timbals_crystal"] = { normal = "OnSpellTickDamage_380Shadow_10%_15Cd" },
		["whispering_fanged_skull"] = { normal = "OnAttackHit_1110AP_35%_15Dur_45Cd", heroic = "OnAttackHit_1250AP_35%_15Dur_45Cd" },
		["wrath_of_cenarius"] = { normal = "OnSpellCastHit_132SP_5%_10Dur" },
	},
	["hidden"] = {
		["darkglow_embroidery"] = { normal = "1spi" },
		["lightweave"] = { normal = "1spi" },
		["lightweave_embroidery"] = { normal = "1spi" },
	},
	["use"] = {
		["energy_siphon"] = { normal = "408SP_20Dur_120Cd" },
		["ephemeral_snowflake"] = { normal = "464Haste_20Dur_120Cd" },
		["fetish_of_volatile_power"] = { normal = "OnSpellCast_57Haste_8Stack_20Dur_120Cd", heroic = "OnSpellCast_64Haste_8Stack_20Dur_120Cd" },
		["hand_mounted_pyro_rocket"] = { normal = "1837Fire_45Cd" },
		["hyperspeed_accelerators"] = { normal = "340Haste_12Dur_60Cd" },
		["living_flame"] = { normal = "505SP_20Dur_120Cd" },
		["maghias_misguided_quill"] = { normal = "716SP_20Dur_120Cd" },
		["mark_of_norgannon"] = { normal = "491Haste_20Dur_120Cd" },
		["mark_of_supremacy"] = { normal = "1024AP_20Dur_120Cd" },
		["nevermelting_ice_crystal"] = { normal = "OnSpellDirectCrit_184Crit_5Stack_20Dur_180Cd_reverse" },
		["platinum_disks_of_battle"] = { normal = "752AP_20Dur_120Cd" },
		["platinum_disks_of_sorcery"] = { normal = "440SP_20Dur_120Cd" },
		["platinum_disks_of_swiftness"] = { normal = "375Haste_20Dur_120Cd" },
		["pyrorocket"] = { normal = "1837Fire_45Cd" },
		["scale_of_fates"] = { normal = "432Haste_20Dur_120Cd" },
		["shard_of_the_crystal_heart"] = { normal = "512Haste_20Dur_120Cd" },
		["sliver_of_pure_ice"] = { normal = "1625Mana_120Cd" },
		["spirit_world_glass"] = { normal = "336Spi_20Dur_120Cd" },
		["talisman_of_resurgence"] = { normal = "599SP_20Dur_120Cd" },
		["talisman_of_volatile_power"] = { normal = "OnSpellCast_57Haste_8Stack_20Dur_120Cd", heroic = "OnSpellCast_64Haste_8Stack_20Dur_120Cd" },
		["vengeance_of_the_forsaken"] = { normal = "OnAttackHit_215AP_5Stack_20Dur_120Cd", heroic = "OnAttackHit_250AP_5Stack_20Dur_120Cd" },
		["victors_call"] = { normal = "OnAttackHit_215AP_5Stack_20Dur_120Cd", heroic = "OnAttackHit_250AP_5Stack_20Dur_120Cd" },
		["wrathstone"] = { normal = "856AP_20Dur_120Cd" },
	},
}
